version: "3.7"
services:
  php8_site:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    container_name: php8_api
    networks:
      - net
    volumes:
      - .:/var/www/html/
    tty: true
    
  db:
    image: mysql:8.0.26
    container_name: mysql_api
    volumes: 
      - ./confs/mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks: 
      - net 

  nginx:
    image: nginx
    volumes:
      - ./volume/nginx.conf:/etc/nginx/nginx.conf
      - ./volume/server.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/
    ports:
        - 80:80
    networks:
      - net

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_BIND_HOST=0.0.0.0
    volumes:
      - "./InitScripts/LocalStack/profile.sh:/docker-entrypoint-initaws.d/profile.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"     
    networks:
      - net

networks:
  net:
    driver: bridge
